### ISSUE TITLE
Issue reaching high amount of data.

### ISSUE THREAD

**Issue by HyCore** [JonathanTreffler/backblaze-personal-wine-container#157]
Hi, i'm currently doing a backup of my ubuntu computer thanks to your service, however i'm running in some issue, as i'm doing a backup of video file made by RED camera that are a few TB each, right now at 260TB backuped it seems to stop and doesn't want to backup the full 580TB that it should, it show as unhealthy, crashing, on portainer so idk what's going on tbh (xvnc & logs show everything is fine until it just freeze), backblaze should support that amount of data right? 
I tried to do a reinstall, but analyzing the drive take for ever. (5days in total last time and 6days until now)
The drive scanning taking long is probably due to scanning hundred of thousand of folder having themself millions of small files for other project, but still, idk what to expect now.

**Comment by traktuner** [comment]
Hey,
the initial scan will take very long, and that is to be expected. When the backup starts, Backblaze will backup files from small to big, so the backup should get faster over time.
If the container can find all files and starts to backup, just leave it alone and you will see some progress.
You can also check the "issues" tab in the settings if some files can not be accesses.
But with that large backup set it will take some time. Depending on your bandwidth and PC resources you can put the threads to 100 (which unfortunately will be used with bigger files and has no impact on small files).
Time will tell - and yes, it should work, also with a large backup set.

**Comment by JonathanTreffler** [comment]
Backblaze Personal is not made for these amounts of data and it will definitely work slowly (more so for many small files, than big ones). This container adds additional overhead, because it needs to use wine to run it on Linux.

I will close this issue, as I consider this much backup data - half a petabyte - to be far out of the range of personal backup space that Backblaze reasonably has to support to call it infinite backup space.

Please look into another backup solution, like LTO tape, that is actually made for this volume of data. Backblaze looses about 3400 dollars on a 580TB customer every month. It is clear, that at some point in the future they will not keep doing that.
And is a backup that can disappear on you (hopefully with some notice at least, but who knows) really a backup ?
