### ISSUE TITLE
Unraid template needs adjusted

### ISSUE THREAD

**Issue by cr8tor456** [JonathanTreffler/backblaze-personal-wine-container#187]
Default template for setting "Storage to back up:" Container Path is set to /backup_volume/ and it never shows up. 
Drive Z shows up but has access to the entire array at root level. 
When changed to /drive_d/ it then shows up as drive D:
Drive Z still shows up though. Not sure if that should go away but i feel like its risky exposing the entire root structure. 

Set to look like below it works as described above should anyone find this and need help.
![container path](https://github.com/user-attachments/assets/c9f84f10-8a1a-442e-a078-04fe5007d1e4)

**Comment by JonathanTreffler** [comment]
The template was created before we had the automatic drive configuration for the /drive_* paths.

I don't have write access to the template directly (because I didn't create my own app registry, but used the selfhosters.net one), so I will probably need to create a PR like the one that originally added the template: https://github.com/selfhosters/unRAID-CA-templates/pull/312

**Comment by JonathanTreffler** [comment]
[PR created](https://github.com/selfhosters/unRAID-CA-templates/pull/520)

**Comment by cr8tor456** [comment]
Thanks for addressing this so quick. I figure its not to hard of a thing to fix, but time is valuable and all so i appreciate you jumping on it.
Will that fix the z drive showing up also or just the path change?

**Comment by JonathanTreffler** [comment]
drive Z is default wine behaviour I think. This will not change that.

**Comment by JonathanTreffler** [comment]
PR merged, closing :)

**Comment by cr8tor456** [comment]
Great that you did this, but i had to give up.
This just does not work. From the weird permissions error, to the z drive that has full access to everything, and it just randomly stops backing up.
I give up. It would be easier to set up a VM and install a windows client.
Thanks for trying though.
I really think you should remove this app from CA though, its just doesnt work.

**Comment by JonathanTreffler** [comment]
The permissions errors are user error, I get that docker permissions can be hard to wrap your head around, but that does not mean it doesn't work.
You probably just have some docker that runs as root and created files owned by root. It's a mistake many people make.
The z drive really does not hurt anything, just don't check it's checkbox in the backblaze settings.
Yes, Backblaze added wine detections and it causes issues for some users.

**Comment by cr8tor456** [comment]
The permissions error is unique to this app. All other apps work fine. Therefore you can blame users all you want, but its only this app that has an issue.

The z drive does not hurt anything, but it also shows sloppy work to be honest. I cant trust an app like this for backing up things when things like this just exist.

I dont think the issues were "wine detection" as you want to label and dismiss. But cool, this app does not work by default. The fact that i had to let you know the template was broken by default tells me no one uses this and thats because it just doesnt work unless you have magically made it work through a bunch of tricks that are not documented anywhere.
Because it doesnt work. Even after making it function, it just doesnt work consistently enough to be a reliable backup solution. You can tell your self differently, but thats cool, dont listen to anyone. There are posts all over that indicate issues with this, including bugs that have been reported and just left for years. I get it, time and all, but again, by default, this doesnt work for anyone. I can say that because i have the most bone dry boring install of unraid.

**Comment by JonathanTreffler** [comment]
> The permissions error is unique to this app. All other apps work fine. Therefore you can blame users all you want, but its only this app that has an issue.

Nope. Other apps just use their OWN files and therefore set the permissions themselves. This app reads the files of OTHER apps, and purposefully does not overwrite those permissions, because that could break other apps.

>  The z drive does not hurt anything, but it also shows sloppy work to be honest

Tell that (don't actually) to the wine team, who implemented that thing. This docker installs wine, we didn't invent it.

Yes some people have issues cause by Backblaze trying to prevent installations on Linux, but there are also many people using this docker successfully.

>  have the most bone dry boring install of unraid.

Unraid hides a lot of complexity, that does not mean it's not there. You need to be able to look under the hood to solve permissions errors, because not all Apps from the store are magically compatible in terms of permissions.
