### ISSUE TITLE
New license

### ISSUE THREAD

**Issue by Atemu** [JonathanTreffler/backblaze-personal-wine-container#2]
Hi, I saw you're putting effort into this and noticed I hadn't licensed it yet. 

It's AGPL now to allow free modification outside of GH's community "license".

I would've created a PR but unfortunately, GH somehow stopped considering your fork as a fork (really odd). You can merge in my master (https://github.com/Atemu/backblaze-personal-wine-container/commit/e83464fcb8a6a8fe719b06a1908e9e509c469b54) manually.

Happy hacking!

**Comment by JonathanTreffler** [comment]
Thanks for clearing up the licensing issue :)

(I requested the separation of the repository tree with the Github support, because having the "forked from" text under the repository name kind of makes it seem like a unstable development effort, that is yet to be merged to upstream and not as an "independent" project.)
