### ISSUE TITLE
Drive D is not mapped as a drive in wine

### ISSUE THREAD

**Issue by Lesani** [JonathanTreffler/backblaze-personal-wine-container#51]
![image](https://user-images.githubusercontent.com/5182104/230888844-d8066a73-e733-493f-baa7-705ecc5c9c7d.png)

Unraid: After a fresh install from the app store (I did delete the whole old config from /mnt/usr/appdata beforehand as well) I find myself finally with a working backblaze but the drive_d is not mounted as a dos device

It is not visible to backblaze and I tried
`sudo docker exec --user app Backblaze_Personal_Backup wine explorer`
to see in the explorer, this is where the screenshot is from

Upon installation of the container everything was left to standard except:
I changed the resolution to 1280:720
I changed the "drive_d" location from /mnt/user to /mnt/user/backblaze

**Comment by Lesani** [comment]
however, all files need to be changed to chmod 0777 in order to be readable by backblaze - which would not be so much of an issue if it didn'T have to be done for every newly added file too. so clearly this is only a workaround, but not a solution.

**Comment by teshiburu2020** [comment]
seems this is still a bug...

**Comment by traktuner** [comment]
> however, all files need to be changed to chmod 0777 in order to be readable by backblaze - which would not be so much of an issue if it didn'T have to be done for every newly added file too. so clearly this is only a workaround, but not a solution.

Hey,
you can add USER_ID and GROUP_ID (with the user you like and who has permissions on the files you'd like to back up) to your docker run command which then will be passed to the docker container.
Backblaze then starts with this UID and GID.
With that, you don't have to run chmod on the files itself.
Please also try to start the container with the :ubuntu22 or :ubuntu20 tag, since this may also fix some other issues (we don't release versioned tags for each update).
