### ISSUE TITLE
Ubuntu 20: Wine kernel32.dll error, status c0000135

### ISSUE THREAD

**Issue by soluml** [JonathanTreffler/backblaze-personal-wine-container#58]
On Ubuntu 20.04 I'm unable to get passed the Wine install step. Googling around, seems like it might be an issue with the version of Wine used by the image. May be related to #44, but I cannot get beyond the initial setup to run any of the VNC tooling.

![image](https://github.com/JonathanTreffler/backblaze-personal-wine-container/assets/589571/8cf0816b-8faa-483b-8d42-f501f2514f10)

**Comment by julzKB** [comment]
same here , had to downgrade to the ubuntu18 image to make it work

**Comment by soluml** [comment]
Ahh, I tried various 20 images but didn't try 18. I'll give that a shot, thanks for mentioning that!

**Comment by traktuner** [comment]
Hey @soluml @julzKB !
Could you please update your image to the latest version (1.6) and let us know if the issue persists?
At container start, the Backblaze updater should show up, please install the latest version (it may take a while for the updater to show up, you'll see a black screen)
Thank you!

**Comment by bradyj04** [comment]
Im having the same issue on unRAID docker, tried the newest v1.6, 1.4 and 1.2, same issue :(

**Comment by bradyj04** [comment]
i got mine working my downgrading to ubuntu 18 and letting it sit for a while. Its just uploading really slow, is there anyway to manually set a speed for upload (the slider in backblaze isnt doing much) it says the tested speed is like .9mbps when the actual speed should be much higher.

**Comment by traktuner** [comment]
> i got mine working my downgrading to ubuntu 18 and letting it sit for a while. Its just uploading really slow, is there anyway to manually set a speed for upload (the slider in backblaze isnt doing much) it says the tested speed is like .9mbps when the actual speed should be much higher.

Hey! Glad you got it working :)
Since it's working you still can try the ubuntu20 and (preferably) ubuntu22 tag. That should also work (ubuntu18 tag will go away eventually since ubuntu18 is end-of-life and won't get any more security updates, wine support is also EOL).
Backblaze uploads tiny files first, which is much slower than uploading large files.
Let it do it's thing and the upload will get faster over time, depending on the files you've selected for backup.

**Comment by bradyj04** [comment]
So, I tried with ubuntu 20 and  22, the issue returned. It seems like an issue with the wine installation. I also had the issue that it stopped scanning my d drive, it would just stop at the end and never end (appdata is not in the mount). Is there any chance this issue gets fixed? Even rolling back to ubuntu 18 i still can't get the drive to sync and sometimes not even boot.

**Comment by traktuner** [comment]
Hey,
please try to start the virtual desktop mode as I described here:
https://github.com/JonathanTreffler/backblaze-personal-wine-container/issues/114#issuecomment-1934760200
It's crucial that you use the :ubuntu20 or :ubuntu22 (or ubuntu:18) tag since there was an issue where winecfg yould not be launched.
I also think that it's not related to an issue with our Backblaze container, but more with the installation on your device or some kind of permission issue.
